export * from './processTransaction'
export * from './processBlock'
export * from './rewindTransactions'
import * as rpc from './rpc'
export { rpc } // Export tudo de './rpc' dentro de um objeto 'rpc'
