version: '3'

services:
  frontend:
    image: gcastilho/frontend:latest
    restart: unless-stopped
    ports:
     - 80:3000
    dns:
      - 10.100.11.30
    network_mode: "bridge"
    environment:
      MAIN_SERVER_IP: ${MAIN_SERVER_IP}
