version: '3'

services:
  main:
    image: gcastilho/frontend:latest
    ports:
     - 80:3000
    restart: unless-stopped
    environment:
      INTERNAL_API_URL: http://10.100.11.80
      PUBLIC_API_URL: http://ttodev.ddns.net:22085/
