version: '3'

services:
  main:
    image: gcastilho/main-server:latest
    restart: unless-stopped
    ports:
     - 80:80
     - 8085:8085
    environment:
      PORT: 80
      MONGODB_URL: ${MONGODB_URL}
