version: "3"

services:
  config-03:
    hostname:
      teste
    container_name: config-03
    image: mongo
    restart: always
    expose:
      - 27019
    entrypoint: ["mongod","--configsvr", "--replSet", "repset", "--port", "27019", "--bind_ip", "0.0.0.0" ]

  config-02:
    hostname: 
      teste
    container_name: config-02
    image: mongo
    expose:
      - 27019
    restart: always
    entrypoint: ["mongod","--configsvr", "--replSet", "repset", "--port", "27019", "--bind_ip", "0.0.0.0" ]

  config-01:
    hostname:
      teste
    image: mongo
    container_name: config-01
    restart: always
    depends_on:
      - config-02
      - config-03
    # build:
    #   context: .
    #   dockerfile: config
    expose:
      - 27019
    links:
      - config-03
      - config-02
    # command: sh mongo --eval 'rs.initiate({ "_id":"repset", "members":[ {"_id":0,"host":"config-01:27017"}, {"_id":1,"host":"config-02:27027"}, {"_id":2,"host":"config-03:27037"} ]})'
    entrypoint: ["/usr/bin/mongod", "--configsvr", "--replSet", "repset", "--port", "27019", "--bind_ip", "0.0.0.0"]

#shard
  shard1a:
    hostname: shard1a
    container_name: shard1a
    depends_on:
      - shard1b
    # build:
    #   context: .
    #   dockerfile: shard
    image: mongo
    expose:
    - 27018
    entrypoint: ["/usr/bin/mongod", "--shardsvr", "--replSet", "shard01", "--port", "27018", "--bind_ip", "0.0.0.0" ]

  shard1b:
    hostname: shard1b
    container_name: shard1b
    image: mongo
    expose:
    - 27018
    entrypoint: ["/usr/bin/mongod", "--shardsvr", "--replSet", "shard01", "--port", "27018", "--bind_ip", "0.0.0.0"]

#router
  mongo-router:
    hostname:
      teste
    container_name: "mongo-router"
    image: mongo
    expose:
      - 27017
    # build:
    #   context: .
    #   dockerfile: router.dockerfile
    depends_on:
      - config-01
      - shard1a
    links:
      - config-03
      - config-02
      - config-01
    ports:
      - 27018:27017
    entrypoint: ["mongos","--configdb", "repset/config-01:27019,config-02:27019,config-03:27019", "--bind_ip", "0.0.0.0" , "--port", "27017" ]

  bootstrap:
    depends_on:
      - mongo-router
    build:
      context: .
      dockerfile: bootstrap.dockerfile
