name: Project's Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup NodeJS 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: 4.2
      - run: npm ci
      - run: npm test
      - run: npm run dep-install
      - run: npm run build
